import type {
  Community,
  CommunityEvent,
  CommunityMember,
  CommunityMessage,
  CommunityNotification,
  CommunityRole,
  CommunitySection,
  CommunitySpace,
  DirectConversation,
  DirectMessage,
  ModerationCase,
} from "@/lib/product-domain";
import {
  SOCIAL_DEMO_COMMUNITIES,
  SOCIAL_DEMO_COMMUNITY_MESSAGES,
  SOCIAL_DEMO_DIRECT_CONVERSATIONS,
  SOCIAL_DEMO_DIRECT_MESSAGES,
  SOCIAL_DEMO_EVENTS,
  SOCIAL_DEMO_MEMBERS,
  SOCIAL_DEMO_MODERATION_CASES,
  SOCIAL_DEMO_NOTIFICATIONS,
  SOCIAL_DEMO_ROLES,
  SOCIAL_DEMO_SECTIONS,
  SOCIAL_DEMO_SPACES,
} from "@/lib/social-demo-data";

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const hoursAgo = (hours: number) => minutesAgo(hours * 60);
const daysAgo = (days: number) => hoursAgo(days * 24);
const hoursFromNow = (hours: number) => new Date(Date.now() + hours * 60 * 60_000).toISOString();

export const COMMUNITIES: Community[] = [
  {
    id: "community-nord",
    slug: "observateurs-du-nord",
    name: "Observateurs du Nord",
    initials: "ON",
    description: "Le ciel, le terrain et les phénomènes du Nord racontés ensemble.",
    about: "Une communauté locale pour comprendre ce qui se passe entre la côte d'Opale, les Flandres, Lille et le Hainaut. Les observations restent humaines, datées et distinctes des données officielles.",
    territory: "Lille · Flandres · Hainaut",
    themes: ["Orages", "Pluie", "Photo", "Pédagogie"],
    access: "public",
    template: "weather",
    memberCount: 2485,
    activeCount: 186,
    observationCount: 43,
    verified: true,
    bannerUrl: "/media/observations/arcus-champs.webp",
    accent: "#65d8f3",
    center: { lat: 50.66, lon: 3.08 },
    rules: [
      "Décrire ce qui est réellement observé, sans inventer de mesure.",
      "Ne jamais se déplacer vers un phénomène dangereux pour publier.",
      "Préserver les adresses, positions exactes et identités sensibles.",
      "Distinguer une observation communautaire d'une information officielle.",
    ],
    featuredSpaceIds: ["space-nord-observations", "space-nord-atlas", "space-nord-general"],
  },
  {
    id: "community-opale",
    slug: "cote-opale-meteo",
    name: "Côte d'Opale Météo",
    initials: "CO",
    description: "Brumes, vent, ciel marin et observations du littoral.",
    about: "Un collectif de terrain autour de Calais, Boulogne-sur-Mer, Dunkerque et Saint-Omer, avec des archives photographiques et des relevés de visibilité.",
    territory: "Côte d'Opale",
    themes: ["Littoral", "Vent", "Brouillard", "Photo"],
    access: "public",
    template: "local",
    memberCount: 1384,
    activeCount: 74,
    observationCount: 28,
    verified: true,
    bannerUrl: "/media/observations/arc-en-ciel-dunes.webp",
    accent: "#4f8cff",
    center: { lat: 50.95, lon: 1.93 },
    rules: [
      "Créditer les médias partagés.",
      "Préciser l'heure et la zone approximative.",
      "Respecter les zones naturelles et les accès interdits.",
    ],
    featuredSpaceIds: ["space-opale-observations", "space-opale-media"],
  },
  {
    id: "community-belgique",
    slug: "ciel-orages-belgique",
    name: "Ciel & Orages Belgique",
    initials: "CB",
    description: "Veille collaborative entre Tournai, Mons, Bruxelles et Namur.",
    about: "Une communauté transfrontalière qui relie les observations visuelles, les discussions pédagogiques et les zones Atlas sans transformer les échanges en alertes officielles.",
    territory: "Belgique francophone",
    themes: ["Orages", "Foudre", "Sécurité"],
    access: "request",
    template: "weather",
    memberCount: 931,
    activeCount: 58,
    observationCount: 21,
    verified: false,
    bannerUrl: "/media/observations/foudre-lointaine.webp",
    accent: "#9b8cff",
    center: { lat: 50.68, lon: 4.2 },
    rules: [
      "Rester à l'abri pendant les phénomènes électriques.",
      "Indiquer clairement les estimations et incertitudes.",
      "Aucune localisation privée en temps réel.",
    ],
    featuredSpaceIds: ["space-belgique-general", "space-belgique-atlas"],
  },
  {
    id: "community-photo",
    slug: "photographes-du-ciel",
    name: "Photographes du ciel",
    initials: "PC",
    description: "Techniques, récits et collections autour des lumières du ciel.",
    about: "Un espace thématique pour apprendre, publier des séries et préparer des sorties respectueuses des lieux et de la météo.",
    territory: "France · Belgique",
    themes: ["Photo", "Nuages", "Aurores", "Timelapse"],
    access: "public",
    template: "photography",
    memberCount: 684,
    activeCount: 41,
    observationCount: 12,
    verified: false,
    bannerUrl: "/media/observations/arc-en-ciel-dunes.webp",
    accent: "#f2c96d",
    center: { lat: 50.55, lon: 2.85 },
    rules: [
      "Toujours créditer l'auteur d'un média.",
      "Ne pas publier de métadonnées de localisation sensibles.",
      "La sécurité passe avant la prise de vue.",
    ],
    featuredSpaceIds: [],
  },
  {
    id: "community-field",
    slug: "terrain-hainaut",
    name: "Terrain Hainaut",
    initials: "TH",
    description: "Coordination locale, entraide et comptes rendus de terrain.",
    about: "Un groupe à accès contrôlé pour préparer des sorties, partager du matériel et documenter les épisodes locaux.",
    territory: "Hainaut transfrontalier",
    themes: ["Terrain", "Entraide", "Formation"],
    access: "private",
    template: "field",
    memberCount: 126,
    activeCount: 19,
    observationCount: 9,
    verified: false,
    bannerUrl: "/media/observations/averse-route.webp",
    accent: "#58d5a5",
    center: { lat: 50.46, lon: 3.55 },
    rules: [
      "Les zones internes restent réservées aux membres.",
      "Le partage de position est ponctuel et volontaire.",
      "Chaque sortie possède un responsable identifié.",
    ],
    featuredSpaceIds: [],
  },
  ...SOCIAL_DEMO_COMMUNITIES,
];

export const COMMUNITY_SECTIONS: CommunitySection[] = [
  { id: "section-nord-essential", communityId: "community-nord", name: "Essentiel", order: 1 },
  { id: "section-nord-discussions", communityId: "community-nord", name: "Discussions", order: 2 },
  { id: "section-nord-field", communityId: "community-nord", name: "Terrain & observations", order: 3 },
  { id: "section-nord-media", communityId: "community-nord", name: "Médias", order: 4 },
  { id: "section-nord-organisation", communityId: "community-nord", name: "Organisation", order: 5 },
  { id: "section-opale-main", communityId: "community-opale", name: "Côte d'Opale", order: 1 },
  { id: "section-belgique-main", communityId: "community-belgique", name: "Veille Belgique", order: 1 },
  ...SOCIAL_DEMO_SECTIONS,
];

export const COMMUNITY_SPACES: CommunitySpace[] = [
  {
    id: "space-nord-announcements",
    communityId: "community-nord",
    sectionId: "section-nord-essential",
    name: "Informations",
    description: "Annonces et décisions de la communauté",
    type: "announcement",
    visibility: "public",
    unreadCount: 1,
  },
  {
    id: "space-nord-start",
    communityId: "community-nord",
    sectionId: "section-nord-essential",
    name: "Commencer ici",
    description: "Règles, repères et premières actions",
    type: "resource",
    visibility: "public",
    unreadCount: 0,
  },
  {
    id: "space-nord-general",
    communityId: "community-nord",
    sectionId: "section-nord-discussions",
    name: "Discussion locale",
    description: "Questions et échanges du quotidien",
    type: "discussion",
    visibility: "members",
    unreadCount: 7,
  },
  {
    id: "space-nord-forecast",
    communityId: "community-nord",
    sectionId: "section-nord-discussions",
    name: "Comprendre la situation",
    description: "Analyses, incertitudes et pédagogie",
    type: "discussion",
    visibility: "public",
    unreadCount: 2,
  },
  {
    id: "space-nord-observations",
    communityId: "community-nord",
    sectionId: "section-nord-field",
    name: "Observations",
    description: "Signaux terrain structurés et confirmations",
    type: "observations",
    visibility: "public",
    unreadCount: 5,
    live: true,
  },
  {
    id: "space-nord-atlas",
    communityId: "community-nord",
    sectionId: "section-nord-field",
    name: "Atlas du Nord",
    description: "Carte filtrée sur le territoire communautaire",
    type: "atlas",
    visibility: "public",
    unreadCount: 0,
    live: true,
  },
  {
    id: "space-nord-media",
    communityId: "community-nord",
    sectionId: "section-nord-media",
    name: "Ciel du jour",
    description: "Photos, vidéos et collections",
    type: "media",
    visibility: "members",
    unreadCount: 4,
  },
  {
    id: "space-nord-events",
    communityId: "community-nord",
    sectionId: "section-nord-organisation",
    name: "Événements",
    description: "Sorties, ateliers et rencontres",
    type: "event",
    visibility: "public",
    unreadCount: 1,
  },
  {
    id: "space-nord-resources",
    communityId: "community-nord",
    sectionId: "section-nord-organisation",
    name: "Ressources sécurité",
    description: "Guides maintenus et protocoles",
    type: "resource",
    visibility: "public",
    unreadCount: 0,
  },
  {
    id: "space-nord-team",
    communityId: "community-nord",
    sectionId: "section-nord-organisation",
    name: "Équipe",
    description: "Coordination des responsables",
    type: "discussion",
    visibility: "role",
    unreadCount: 0,
  },
  {
    id: "space-opale-observations",
    communityId: "community-opale",
    sectionId: "section-opale-main",
    name: "Observations littorales",
    description: "Visibilité, vent et état du ciel",
    type: "observations",
    visibility: "public",
    unreadCount: 3,
  },
  {
    id: "space-opale-media",
    communityId: "community-opale",
    sectionId: "section-opale-main",
    name: "Galerie du littoral",
    description: "Séries et archives côtières",
    type: "media",
    visibility: "public",
    unreadCount: 2,
  },
  {
    id: "space-opale-general",
    communityId: "community-opale",
    sectionId: "section-opale-main",
    name: "Le café du port",
    description: "Conversation locale",
    type: "discussion",
    visibility: "members",
    unreadCount: 0,
  },
  {
    id: "space-belgique-general",
    communityId: "community-belgique",
    sectionId: "section-belgique-main",
    name: "Veille orageuse",
    description: "Échanges et confirmations locales",
    type: "discussion",
    visibility: "members",
    unreadCount: 4,
  },
  {
    id: "space-belgique-atlas",
    communityId: "community-belgique",
    sectionId: "section-belgique-main",
    name: "Atlas Belgique",
    description: "Vue territoriale de la communauté",
    type: "atlas",
    visibility: "members",
    unreadCount: 0,
  },
  ...SOCIAL_DEMO_SPACES,
];

export const COMMUNITY_EVENTS: CommunityEvent[] = ([
  {
    id: "event-radar-workshop",
    communityId: "community-nord",
    title: "Atelier : lire le radar sans surinterpréter",
    summary: "Une session courte pour relier réflectivité, déplacement et observations au sol.",
    startsAt: hoursFromNow(26),
    endsAt: hoursFromNow(28),
    place: "Maison des associations · Lille",
    access: "public",
    format: "hybrid",
    participantCount: 42,
    interestedCount: 88,
    imageUrl: "/media/observations/averse-route.webp",
    lat: 50.631,
    lon: 3.057,
  },
  {
    id: "event-opale-photo",
    communityId: "community-opale",
    title: "Sortie lumières du littoral",
    summary: "Préparation, sécurité et prises de vue depuis une zone autorisée.",
    startsAt: hoursFromNow(54),
    endsAt: hoursFromNow(58),
    place: "Digue de Malo · zone confirmée la veille",
    access: "members",
    format: "onsite",
    participantCount: 18,
    interestedCount: 31,
    imageUrl: "/media/observations/arc-en-ciel-dunes.webp",
    lat: 51.05,
    lon: 2.36,
  },
  {
    id: "event-belgium-briefing",
    communityId: "community-belgique",
    title: "Briefing de veille transfrontalière",
    summary: "Organisation des espaces et rappel des règles de confirmation.",
    startsAt: hoursFromNow(6),
    endsAt: hoursFromNow(7),
    place: "En ligne",
    access: "members",
    format: "online",
    participantCount: 27,
    interestedCount: 45,
    imageUrl: "/media/observations/foudre-lointaine.webp",
    lat: 50.65,
    lon: 4.0,
  },
  ...SOCIAL_DEMO_EVENTS,
] as CommunityEvent[]).sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());

export const COMMUNITY_ROLES: CommunityRole[] = [
  {
    id: "role-owner",
    communityId: "community-nord",
    name: "Propriétaire",
    summary: "Responsabilité finale et paramètres critiques.",
    color: "#ff7388",
    priority: 100,
    critical: true,
    permissions: ["Administrer la communauté", "Transférer la propriété", "Gérer les rôles"],
  },
  {
    id: "role-admin",
    communityId: "community-nord",
    name: "Administrateur",
    summary: "Structure, accès et fonctionnement global.",
    color: "#9b8cff",
    priority: 80,
    critical: true,
    permissions: ["Gérer les espaces", "Gérer les membres", "Voir le journal"],
  },
  {
    id: "role-moderator",
    communityId: "community-nord",
    name: "Modérateur",
    summary: "Protection des membres et qualité des contenus.",
    color: "#65d8f3",
    priority: 60,
    critical: false,
    permissions: ["Traiter les signalements", "Ralentir un espace", "Avertir un membre"],
  },
  {
    id: "role-observer",
    communityId: "community-nord",
    name: "Observateur vérifié",
    summary: "Contributions terrain reconnues dans ce contexte.",
    color: "#58d5a5",
    priority: 40,
    critical: false,
    permissions: ["Publier une observation", "Confirmer localement"],
  },
  {
    id: "role-member",
    communityId: "community-nord",
    name: "Membre",
    summary: "Participation normale aux espaces ouverts.",
    color: "#4f8cff",
    priority: 20,
    critical: false,
    permissions: ["Lire", "Commenter", "Réagir"],
  },
  {
    id: "role-new",
    communityId: "community-nord",
    name: "Nouveau membre",
    summary: "Accès progressif avec limites anti-spam visibles.",
    color: "#89a2b8",
    priority: 10,
    critical: false,
    permissions: ["Lire", "Réagir", "Publier avec délai"],
  },
  ...SOCIAL_DEMO_ROLES,
];

export const COMMUNITY_MEMBERS: CommunityMember[] = [
  { id: "member-adele", communityId: "community-nord", displayName: "Adèle Martin", handle: "@adele_ciel", initials: "AM", roleId: "role-owner", joinedAt: daysAgo(640), contributionCount: 418, presence: "active", accent: "#9b8cff" },
  { id: "author-lena", communityId: "community-nord", displayName: "Léna Météo", handle: "@lena_meteo", initials: "LM", roleId: "role-moderator", joinedAt: daysAgo(420), contributionCount: 286, presence: "available", accent: "#65d8f3" },
  { id: "author-nord-ciel", communityId: "community-nord", displayName: "Nord Ciel", handle: "@nordciel", initials: "NC", roleId: "role-observer", joinedAt: daysAgo(310), contributionCount: 193, presence: "active", accent: "#4f8cff" },
  { id: "author-claire", communityId: "community-nord", displayName: "Claire Vents", handle: "@clairevents", initials: "CV", roleId: "role-observer", joinedAt: daysAgo(190), contributionCount: 144, presence: "busy", accent: "#ff8f70" },
  { id: "member-nassim", communityId: "community-nord", displayName: "Nassim L.", handle: "@nassim_local", initials: "NL", roleId: "role-member", joinedAt: daysAgo(88), contributionCount: 36, presence: "available", accent: "#58d5a5" },
  { id: "member-romane", communityId: "community-nord", displayName: "Romane", handle: "@romane_photo", initials: "RO", roleId: "role-member", joinedAt: daysAgo(54), contributionCount: 29, presence: "offline", accent: "#f2c96d" },
  { id: "member-yanis", communityId: "community-nord", displayName: "Yanis D.", handle: "@yanis59", initials: "YD", roleId: "role-new", joinedAt: daysAgo(3), contributionCount: 2, presence: "active", accent: "#89a2b8" },
  ...SOCIAL_DEMO_MEMBERS,
];

export const COMMUNITY_MESSAGES: CommunityMessage[] = ([
  {
    id: "community-message-1",
    communityId: "community-nord",
    spaceId: "space-nord-announcements",
    authorId: "member-adele",
    authorName: "Adèle Martin",
    authorInitials: "AM",
    body: "Le guide de confirmation des observations a été simplifié. Les données officielles et les signalements humains restent clairement séparés.",
    createdAt: hoursAgo(3),
    kind: "announcement",
    reactions: { "Compris": 42 },
  },
  {
    id: "community-message-2",
    communityId: "community-nord",
    spaceId: "space-nord-general",
    authorId: "author-lena",
    authorName: "Léna Météo",
    authorInitials: "LM",
    body: "Les averses restent très irrégulières. Entre deux communes proches, la différence peut être nette : pensez à indiquer une zone plutôt qu'une adresse.",
    createdAt: minutesAgo(18),
    kind: "message",
    reactions: { "Utile": 16, "Merci": 8 },
  },
  {
    id: "community-message-3",
    communityId: "community-nord",
    spaceId: "space-nord-general",
    authorId: "member-nassim",
    authorName: "Nassim L.",
    authorInitials: "NL",
    body: "À Lambersart le sol est humide mais je n'observe plus de pluie depuis une dizaine de minutes.",
    createdAt: minutesAgo(11),
    kind: "message",
    replyToId: "community-message-2",
    reactions: { "Merci": 4 },
  },
  {
    id: "community-message-4",
    communityId: "community-nord",
    spaceId: "space-nord-forecast",
    authorId: "author-nord-ciel",
    authorName: "Nord Ciel",
    authorInitials: "NC",
    body: "Le composite montre surtout une organisation en petites cellules. Une couleur forte reste une réflectivité : elle ne donne pas à elle seule la quantité exacte au sol.",
    createdAt: minutesAgo(32),
    kind: "resource",
    reactions: { "Utile": 23 },
  },
  {
    id: "community-message-5",
    communityId: "community-nord",
    spaceId: "space-nord-observations",
    authorId: "author-claire",
    authorName: "Claire Vents",
    authorInitials: "CV",
    body: "Rafale brève et rideau de pluie observés au sud de Tournai. L'observation a été reliée à Atlas avec une position volontairement approximative.",
    createdAt: minutesAgo(9),
    kind: "observation",
    reactions: { "Confirmé": 7, "Merci": 3 },
  },
  {
    id: "community-message-6",
    communityId: "community-nord",
    spaceId: "space-nord-start",
    authorId: "member-adele",
    authorName: "Adèle Martin",
    authorInitials: "AM",
    body: "Bienvenue. Commencez par lire les règles essentielles, ouvrez Atlas du Nord puis suivez un espace qui correspond à votre zone.",
    createdAt: daysAgo(4),
    kind: "resource",
  },
  {
    id: "community-message-7",
    communityId: "community-opale",
    spaceId: "space-opale-general",
    authorId: "author-opale",
    authorName: "Côte d'Opale Météo",
    authorInitials: "CO",
    body: "La visibilité s'améliore nettement au sud de Calais. Les dernières nappes restent proches des canaux.",
    createdAt: minutesAgo(26),
    kind: "message",
  },
  {
    id: "community-message-8",
    communityId: "community-belgique",
    spaceId: "space-belgique-general",
    authorId: "author-jules",
    authorName: "Jules D.",
    authorInitials: "JD",
    body: "Activité électrique lointaine vers l'est de Tournai, observée depuis un lieu fermé.",
    createdAt: minutesAgo(14),
    kind: "observation",
  },
  ...SOCIAL_DEMO_COMMUNITY_MESSAGES,
] as CommunityMessage[]).sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());

export const DIRECT_CONVERSATIONS: DirectConversation[] = [
  {
    id: "conversation-lena",
    participantIds: ["author-lena"],
    participantNames: ["Léna Météo"],
    participantInitials: ["LM"],
    title: "Léna Météo",
    preview: "Je te renvoie le guide de confirmation.",
    updatedAt: minutesAgo(7),
    unreadCount: 1,
    request: false,
    accent: "#65d8f3",
  },
  {
    id: "conversation-team",
    participantIds: ["member-adele", "author-nord-ciel"],
    participantNames: ["Adèle", "Nord Ciel"],
    participantInitials: ["AM", "NC"],
    title: "Préparation atelier radar",
    preview: "Le déroulé tient en quarante-cinq minutes.",
    updatedAt: hoursAgo(2),
    unreadCount: 0,
    request: false,
    accent: "#9b8cff",
  },
  {
    id: "conversation-request",
    participantIds: ["member-unknown"],
    participantNames: ["Camille R."],
    participantInitials: ["CR"],
    title: "Demande de message",
    preview: "Bonjour, puis-je utiliser votre photo dans une ressource ?",
    updatedAt: hoursAgo(5),
    unreadCount: 1,
    request: true,
    accent: "#f2c96d",
  },
  ...SOCIAL_DEMO_DIRECT_CONVERSATIONS,
].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());

export const DIRECT_MESSAGES: DirectMessage[] = [
  { id: "direct-1", conversationId: "conversation-lena", authorId: "author-lena", authorName: "Léna Météo", body: "Ton observation était claire. La position approximative est suffisante pour ce type de confirmation.", createdAt: minutesAgo(28) },
  { id: "direct-2", conversationId: "conversation-lena", authorId: "local-user", authorName: "XimaM", body: "Merci. J'hésitais sur la façon de décrire la visibilité.", createdAt: minutesAgo(19) },
  { id: "direct-3", conversationId: "conversation-lena", authorId: "author-lena", authorName: "Léna Météo", body: "Je te renvoie le guide de confirmation. Il y a maintenant un exemple très court.", createdAt: minutesAgo(7) },
  { id: "direct-4", conversationId: "conversation-team", authorId: "member-adele", authorName: "Adèle", body: "J'ai regroupé les exemples pour ne pas surcharger la présentation.", createdAt: hoursAgo(3) },
  { id: "direct-5", conversationId: "conversation-team", authorId: "author-nord-ciel", authorName: "Nord Ciel", body: "Le déroulé tient en quarante-cinq minutes. On gardera quinze minutes de questions.", createdAt: hoursAgo(2) },
  { id: "direct-6", conversationId: "conversation-request", authorId: "member-unknown", authorName: "Camille R.", body: "Bonjour, puis-je utiliser votre photo dans une ressource pédagogique ? Je conserverai le crédit.", createdAt: hoursAgo(5) },
  ...SOCIAL_DEMO_DIRECT_MESSAGES,
];

export const COMMUNITY_NOTIFICATIONS: CommunityNotification[] = ([
  { id: "notification-reply", communityId: "community-nord", type: "reply", priority: "high", title: "Léna a répondu à votre observation", body: "La position approximative est suffisante pour cette confirmation.", createdAt: minutesAgo(7), targetSpaceId: "space-nord-observations" },
  { id: "notification-event", communityId: "community-nord", type: "event", priority: "high", title: "Atelier radar demain", body: "Le lieu et le programme de l'atelier ont été confirmés.", createdAt: minutesAgo(42), targetSpaceId: "space-nord-events" },
  { id: "notification-observation", communityId: "community-nord", type: "observation", priority: "normal", title: "Nouvelle observation près de Lille", body: "Un rideau de pluie et une rafale ont été signalés au sud-est.", createdAt: hoursAgo(1), targetObservationId: "seed-storm" },
  { id: "notification-mention", communityId: "community-nord", type: "mention", priority: "high", title: "Vous avez été mentionné", body: "Nord Ciel vous invite à relire le résumé de l'atelier.", createdAt: hoursAgo(2), targetSpaceId: "space-nord-general" },
  { id: "notification-membership", communityId: "community-belgique", type: "membership", priority: "normal", title: "Demande d'adhésion reçue", body: "Ciel & Orages Belgique examine habituellement les demandes sous 24 heures.", createdAt: hoursAgo(4) },
  { id: "notification-security", type: "security", priority: "critical", title: "Sécurité du compte", body: "Aucune authentification distante n'est active dans cette version locale.", createdAt: daysAgo(1) },
  { id: "notification-reaction", communityId: "community-nord", type: "reply", priority: "low", title: "3 personnes ont trouvé votre note utile", body: "Les réactions faibles sont regroupées pour limiter le bruit.", createdAt: daysAgo(1) },
  ...SOCIAL_DEMO_NOTIFICATIONS,
] as CommunityNotification[]).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

export const MODERATION_CASES: ModerationCase[] = [
  {
    id: "case-location",
    communityId: "community-nord",
    priority: "urgent",
    category: "safety",
    title: "Adresse précise visible dans une observation",
    summary: "Le média semble révéler une adresse privée alors que la publication est publique.",
    reportedContent: "Photo avec numéro de rue et coordonnées exactes dans la légende.",
    reportedMemberId: "member-yanis",
    createdAt: minutesAgo(21),
    status: "open",
    previousActions: 0,
  },
  {
    id: "case-misinformation",
    communityId: "community-nord",
    priority: "high",
    category: "misinformation",
    title: "Message présenté comme une alerte officielle",
    summary: "Une publication communautaire utilise un ton et un visuel qui peuvent être confondus avec une alerte.",
    reportedContent: "ALERTE ROUGE IMMÉDIATE — évacuation de toute la métropole.",
    reportedMemberId: "member-nassim",
    createdAt: hoursAgo(2),
    status: "reviewing",
    previousActions: 1,
  },
  {
    id: "case-spam",
    communityId: "community-nord",
    priority: "normal",
    category: "spam",
    title: "Messages répétés dans trois espaces",
    summary: "Quatorze messages identiques ont été publiés en moins d'une minute.",
    reportedContent: "Lien promotionnel répété sans contexte territorial.",
    reportedMemberId: "member-yanis",
    createdAt: hoursAgo(5),
    status: "open",
    previousActions: 0,
  },
  {
    id: "case-quality",
    communityId: "community-nord",
    priority: "low",
    category: "quality",
    title: "Observation classée dans le mauvais espace",
    summary: "Le contenu est utile mais appartient à la galerie plutôt qu'au suivi en direct.",
    reportedContent: "Série photographique prise la semaine dernière.",
    reportedMemberId: "member-romane",
    createdAt: daysAgo(1),
    status: "open",
    previousActions: 0,
  },
  ...SOCIAL_DEMO_MODERATION_CASES,
];
