import type { Observation, ObservationCategory } from "@/lib/types";
import { SOCIAL_DEMO_OBSERVATIONS } from "@/lib/social-demo-data";

export const DEMO_IMAGES = {
  orage: "/media/observations/foudre-lointaine.webp",
  pluie: "/media/observations/averse-route.webp",
  grêle: "/media/observations/grele-terrasse.webp",
  rafales: "/media/observations/arcus-champs.webp",
  brouillard: "/media/observations/brouillard-canal.webp",
  "arc-en-ciel": "/media/observations/arc-en-ciel-dunes.webp",
  nuage: "/media/observations/arcus-champs.webp",
} satisfies Partial<Record<ObservationCategory, string>>;

export function seededObservations(): Observation[] {
  const now = Date.now();
  return [
    {
      id: "seed-storm",
      nickname: "Storm_chaser",
      category: "pluie",
      phenomena: ["pluie", "rafales", "orage"],
      intensity: 4,
      details: "Averse intense et fortes rafales de vent.",
      lat: 50.523,
      lon: 3.177,
      createdAt: new Date(now - 5 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.pluie,
      likes: 24,
      place: "Templeuve-en-Pévèle",
      expiresAt: new Date(now + 55 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-rain",
      nickname: "Léna Météo",
      category: "pluie",
      phenomena: ["pluie", "rafales"],
      intensity: 3,
      details: "Averse soutenue, visibilité réduite par moments.",
      lat: 50.685,
      lon: 2.883,
      createdAt: new Date(now - 8 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.pluie,
      likes: 8,
      place: "Armentières",
      expiresAt: new Date(now + 42 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-cloud",
      nickname: "Nord Ciel",
      category: "nuage",
      phenomena: ["nuage"],
      intensity: 2,
      details: "Base nuageuse très sombre vers le nord-ouest.",
      lat: 50.598,
      lon: 2.629,
      createdAt: new Date(now - 15 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.nuage,
      likes: 11,
      place: "Béthune",
      expiresAt: new Date(now + 105 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-wind",
      nickname: "Chloé Photo",
      category: "rafales",
      phenomena: ["rafales", "pluie"],
      intensity: 3,
      details: "Rafales visibles dans les arbres, pluie faible.",
      lat: 50.371,
      lon: 3.080,
      createdAt: new Date(now - 20 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.rafales,
      likes: 5,
      place: "Douai",
      expiresAt: new Date(now + 30 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-coast",
      nickname: "Côte Opale",
      category: "pluie",
      phenomena: ["pluie"],
      intensity: 2,
      details: "Averse côtière qui remonte vers l'intérieur des terres.",
      lat: 50.868,
      lon: 1.871,
      createdAt: new Date(now - 62 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.pluie,
      likes: 16,
      place: "Guines",
      expiresAt: new Date(now + 75 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-dunkerque",
      nickname: "Dunes du Nord",
      category: "pluie",
      phenomena: ["pluie", "rafales"],
      intensity: 2,
      details: "Rideau de pluie visible sur la mer.",
      lat: 51.017,
      lon: 2.312,
      createdAt: new Date(now - 12 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.pluie,
      likes: 6,
      place: "Gravelines",
      expiresAt: new Date(now + 48 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-tournai",
      nickname: "Ciel Wallon",
      category: "orage",
      phenomena: ["orage", "foudre", "pluie"],
      intensity: 4,
      details: "Front orageux très actif au-dessus de Tournai.",
      lat: 50.624,
      lon: 3.328,
      createdAt: new Date(now - 5 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.orage,
      likes: 19,
      place: "Froyennes",
      expiresAt: new Date(now + 70 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-stamand",
      nickname: "Parc Scarpe",
      category: "pluie",
      phenomena: ["pluie", "rafales"],
      intensity: 3,
      details: "Pluie battante sur la forêt de Raismes.",
      lat: 50.443,
      lon: 3.422,
      createdAt: new Date(now - 7 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.pluie,
      likes: 9,
      place: "Saint-Amand-les-Eaux",
      expiresAt: new Date(now + 52 * 60_000).toISOString(),
      isSeed: true,
    },
    {
      id: "seed-lille",
      nickname: "Léo Weppes",
      category: "nuage",
      phenomena: ["nuage", "brouillard"],
      intensity: 2,
      details: "Base sombre en approche sur la métropole.",
      lat: 50.641,
      lon: 2.942,
      createdAt: new Date(now - 3 * 60_000).toISOString(),
      imageUrl: DEMO_IMAGES.nuage,
      likes: 4,
      place: "Lille",
      expiresAt: new Date(now + 95 * 60_000).toISOString(),
      isSeed: true,
    },
    ...SOCIAL_DEMO_OBSERVATIONS,
  ];
}
