import type {
  LearningLesson,
  ProductAuthor,
  ProductPost,
  RoomMessage,
  StormRoom,
} from "@/lib/product-domain";
import {
  SOCIAL_DEMO_AUTHORS,
  SOCIAL_DEMO_COMMENTS_BY_TARGET,
  SOCIAL_DEMO_POSTS,
  SOCIAL_DEMO_ROOM_MESSAGES,
  SOCIAL_DEMO_ROOMS,
} from "@/lib/social-demo-data";

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const hoursAgo = (hours: number) => minutesAgo(hours * 60);

export const PRODUCT_AUTHORS: ProductAuthor[] = [
  {
    id: "author-lena",
    displayName: "Léna Météo",
    handle: "@lena_meteo",
    initials: "LM",
    region: "Métropole lilloise",
    role: "reliable",
    accent: "#62f2dc",
  },
  {
    id: "author-nord-ciel",
    displayName: "Nord Ciel",
    handle: "@nordciel",
    initials: "NC",
    region: "Hauts-de-France",
    role: "creator",
    accent: "#8abfff",
  },
  {
    id: "author-opale",
    displayName: "Côte d'Opale Météo",
    handle: "@opale_meteo",
    initials: "OM",
    region: "Littoral",
    role: "association",
    accent: "#ffd46a",
  },
  {
    id: "author-jules",
    displayName: "Jules D.",
    handle: "@jules_observe",
    initials: "JD",
    region: "Tournai",
    role: "member",
    accent: "#a16fff",
  },
  {
    id: "author-claire",
    displayName: "Claire Vents",
    handle: "@clairevents",
    initials: "CV",
    region: "Valenciennes",
    role: "reliable",
    accent: "#ff8f70",
  },
  ...SOCIAL_DEMO_AUTHORS,
];

export const PRODUCT_POSTS: ProductPost[] = ([
  {
    id: "post-arcus",
    authorId: "author-nord-ciel",
    kind: "analysis",
    title: "L'arcus traverse les Flandres",
    body: "La structure reste bien organisée mais son activité électrique faiblit. Les rafales arrivent quelques minutes avant le rideau de pluie.",
    imageUrl: "/media/observations/arcus-champs.webp",
    place: "Bailleul",
    lat: 50.739,
    lon: 2.736,
    phenomena: ["orage", "rafales", "pluie"],
    publishedAt: minutesAgo(8),
    likes: 86,
    comments: 14,
    shares: 19,
    useful: true,
  },
  {
    id: "post-rain-road",
    authorId: "author-lena",
    kind: "observation",
    title: "Rideau de pluie au sud-est de Lille",
    body: "Visibilité réduite sur quelques kilomètres. La chaussée se charge rapidement en eau, sans inondation observée.",
    imageUrl: "/media/observations/averse-route.webp",
    place: "Templeuve-en-Pévèle",
    lat: 50.523,
    lon: 3.177,
    phenomena: ["pluie", "rafales"],
    publishedAt: minutesAgo(13),
    likes: 42,
    comments: 8,
    shares: 7,
    observationId: "seed-storm",
    useful: true,
  },
  {
    id: "post-lightning",
    authorId: "author-jules",
    kind: "photo",
    title: "Deux impacts visibles vers l'est",
    body: "Photo prise depuis un point fixe et abrité. L'orage reste éloigné, aucun déplacement vers la cellule.",
    imageUrl: "/media/observations/foudre-lointaine.webp",
    place: "Tournai",
    lat: 50.605,
    lon: 3.389,
    phenomena: ["foudre", "orage"],
    publishedAt: minutesAgo(24),
    likes: 118,
    comments: 21,
    shares: 31,
    useful: true,
  },
  {
    id: "post-hail",
    authorId: "author-claire",
    kind: "observation",
    title: "Grêle brève mais dense",
    body: "Les grêlons sont petits et l'épisode a duré moins de quatre minutes. Les sols restent blanchis par endroits.",
    imageUrl: "/media/observations/grele-terrasse.webp",
    place: "Saint-Amand-les-Eaux",
    lat: 50.447,
    lon: 3.428,
    phenomena: ["grêle", "orage"],
    publishedAt: minutesAgo(36),
    likes: 64,
    comments: 11,
    shares: 9,
  },
  {
    id: "post-fog",
    authorId: "author-opale",
    kind: "recap",
    title: "Le brouillard matinal s'est levé tardivement",
    body: "Retour sur la nappe très locale observée le long des canaux. La visibilité est redevenue normale avant 10 h.",
    imageUrl: "/media/observations/brouillard-canal.webp",
    place: "Saint-Omer",
    lat: 50.748,
    lon: 2.252,
    phenomena: ["brouillard"],
    publishedAt: hoursAgo(4),
    likes: 39,
    comments: 5,
    shares: 6,
  },
  {
    id: "post-rainbow",
    authorId: "author-opale",
    kind: "photo",
    title: "Éclaircie spectaculaire sur les dunes",
    body: "L'averse vient de gagner la mer. Double arc visible pendant environ trois minutes.",
    imageUrl: "/media/observations/arc-en-ciel-dunes.webp",
    place: "Bray-Dunes",
    lat: 51.077,
    lon: 2.515,
    phenomena: ["arc-en-ciel", "pluie"],
    publishedAt: hoursAgo(7),
    likes: 152,
    comments: 18,
    shares: 44,
  },
  ...SOCIAL_DEMO_POSTS,
] as ProductPost[]).sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());

export const PRODUCT_COMMENTS_BY_TARGET = SOCIAL_DEMO_COMMENTS_BY_TARGET;

export const PRODUCT_ROOMS: StormRoom[] = [
  {
    id: "room-flandres",
    title: "Ligne orageuse des Flandres",
    shortTitle: "Orages Flandres",
    summary: "Suivi collectif de la ligne entre Dunkerque, Bailleul et la métropole lilloise.",
    area: "Flandres · Lille",
    phenomenon: "orage",
    status: "active",
    startedAt: hoursAgo(2),
    updatedAt: minutesAgo(3),
    lat: 50.83,
    lon: 2.74,
    participantCount: 184,
    observationCount: 31,
    messageCount: 96,
    sourceCount: 3,
    imageUrl: "/media/observations/arcus-champs.webp",
  },
  {
    id: "room-hainaut",
    title: "Averses du Hainaut",
    shortTitle: "Averses Hainaut",
    summary: "Observations et évolution des cellules entre Tournai, Valenciennes et Mons.",
    area: "Hainaut transfrontalier",
    phenomenon: "pluie",
    status: "watching",
    startedAt: hoursAgo(1),
    updatedAt: minutesAgo(9),
    lat: 50.48,
    lon: 3.55,
    participantCount: 72,
    observationCount: 14,
    messageCount: 38,
    sourceCount: 2,
    imageUrl: "/media/observations/averse-route.webp",
  },
  {
    id: "room-opale-archive",
    title: "Brouillards de la Côte d'Opale",
    shortTitle: "Brouillard Opale",
    summary: "Archive expliquée de l'épisode côtier et des fortes variations de visibilité.",
    area: "Calais · Dunkerque",
    phenomenon: "brouillard",
    status: "archived",
    startedAt: hoursAgo(30),
    updatedAt: hoursAgo(20),
    lat: 50.98,
    lon: 1.98,
    participantCount: 96,
    observationCount: 22,
    messageCount: 61,
    sourceCount: 2,
    imageUrl: "/media/observations/brouillard-canal.webp",
  },
  ...SOCIAL_DEMO_ROOMS,
];

export const PRODUCT_ROOM_MESSAGES: RoomMessage[] = [
  {
    id: "room-message-1",
    roomId: "room-flandres",
    authorId: "author-lena",
    authorName: "Léna Météo",
    body: "Le front vient de franchir Bailleul. Rafales nettes environ deux minutes avant la pluie.",
    createdAt: minutesAgo(6),
    kind: "confirmation",
  },
  {
    id: "room-message-2",
    roomId: "room-flandres",
    authorId: "author-nord-ciel",
    authorName: "Nord Ciel",
    body: "L'activité électrique reste surtout sur la partie nord. Suivi depuis un lieu abrité.",
    createdAt: minutesAgo(4),
    kind: "message",
  },
  {
    id: "room-message-3",
    roomId: "room-hainaut",
    authorId: "author-claire",
    authorName: "Claire Vents",
    body: "Averse soutenue signalée à l'ouest de Valenciennes, déplacement lent vers l'est.",
    createdAt: minutesAgo(11),
    kind: "confirmation",
  },
  ...SOCIAL_DEMO_ROOM_MESSAGES,
];

export const PRODUCT_LESSONS: LearningLesson[] = [
  {
    id: "lesson-radar",
    category: "radar",
    title: "Lire une image radar sans se tromper",
    summary: "Comprendre la réflectivité, la transparence et les limites d'un composite radar.",
    durationMinutes: 6,
    level: "Découvrir",
    imageUrl: "/media/observations/averse-route.webp",
    paragraphs: [
      "Le radar mesure l'énergie renvoyée par les hydrométéores. Weyra affiche ici la réflectivité en dBZ, pas directement une quantité de pluie au sol.",
      "Une couleur plus forte traduit généralement un écho plus intense, mais la grêle, la fonte de neige ou certains artefacts peuvent modifier cette lecture.",
      "La carte devient plus utile lorsqu'on compare le radar avec des observations récentes et datées.",
    ],
    keyPoints: ["Toujours regarder l'heure du scan", "Comparer plusieurs trames", "Ne pas confondre dBZ et mm/h"],
  },
  {
    id: "lesson-arcus",
    category: "clouds",
    title: "Reconnaître un arcus",
    summary: "Identifier ce nuage bas qui précède parfois une rafale et une forte averse.",
    durationMinutes: 5,
    level: "Comprendre",
    imageUrl: "/media/observations/arcus-champs.webp",
    paragraphs: [
      "Un arcus est un nuage horizontal attaché à la base d'un orage. Il marque souvent la limite entre l'air froid sortant de la cellule et l'air plus chaud environnant.",
      "Son passage peut être accompagné d'une hausse rapide du vent, puis d'une forte pluie.",
      "L'observation doit toujours se faire depuis un endroit sûr, sans se déplacer vers l'orage.",
    ],
    keyPoints: ["Structure basse et horizontale", "Rafale possible avant la pluie", "Observer depuis un abri"],
  },
  {
    id: "lesson-lightning",
    category: "safety",
    title: "Orage : les bons réflexes",
    summary: "Une fiche simple pour réduire l'exposition à la foudre.",
    durationMinutes: 4,
    level: "Découvrir",
    imageUrl: "/media/observations/foudre-lointaine.webp",
    paragraphs: [
      "Dès que le tonnerre est audible, la foudre peut atteindre votre zone. Cherchez un bâtiment fermé ou un véhicule à toit métallique.",
      "Éloignez-vous des points hauts, arbres isolés, plans d'eau et structures métalliques.",
      "Weyra contextualise la situation mais les consignes des autorités restent prioritaires.",
    ],
    keyPoints: ["S'abriter tôt", "Éviter les points exposés", "Suivre les consignes officielles"],
  },
  {
    id: "lesson-hail",
    category: "winter",
    title: "Grêle, grésil ou neige roulée ?",
    summary: "Différencier trois précipitations souvent confondues.",
    durationMinutes: 7,
    level: "Approfondir",
    imageUrl: "/media/observations/grele-terrasse.webp",
    paragraphs: [
      "La grêle se forme dans les forts courants ascendants convectifs et peut présenter plusieurs couches de glace.",
      "Le grésil est plus petit et plus friable, tandis que la neige roulée ressemble à de petites billes blanches opaques.",
      "Une photo avec un objet d'échelle aide la communauté, sans exposer d'information privée.",
    ],
    keyPoints: ["Observer la taille", "Décrire la texture", "Ajouter une échelle sûre"],
  },
  {
    id: "lesson-fog",
    category: "clouds",
    title: "Pourquoi le brouillard reste local",
    summary: "Relief, humidité et vent expliquent les forts écarts de visibilité.",
    durationMinutes: 5,
    level: "Comprendre",
    imageUrl: "/media/observations/brouillard-canal.webp",
    paragraphs: [
      "Le brouillard apparaît lorsque l'air proche du sol atteint la saturation. Les vallées, canaux et zones humides peuvent le renforcer localement.",
      "Un vent faible suffit parfois à déplacer ou dissiper rapidement une nappe.",
      "Les observations de visibilité complètent particulièrement bien les données automatiques.",
    ],
    keyPoints: ["Phénomène très local", "Vent faible mais décisif", "Visibilité à décrire précisément"],
  },
  {
    id: "lesson-wind",
    category: "wind",
    title: "Estimer une rafale sans instrument",
    summary: "Utiliser des indices visuels sans transformer une impression en mesure.",
    durationMinutes: 6,
    level: "Comprendre",
    imageUrl: "/media/observations/arc-en-ciel-dunes.webp",
    paragraphs: [
      "Sans anémomètre, une observation de vent reste qualitative. Décrivez les effets visibles plutôt qu'une vitesse supposée.",
      "Branches en mouvement, objets déplacés et difficulté à marcher sont des indices, mais leur interprétation dépend du contexte.",
      "Dans Weyra, une intensité communautaire ne remplace jamais une mesure officielle.",
    ],
    keyPoints: ["Décrire les effets", "Éviter les vitesses inventées", "Distinguer observation et mesure"],
  },
];
